[compat]
Arpack = "1"
BenchmarkTools = "1"
Compat = "4"
DataFrames = "1"
Distributions = "0.25"
Documenter = "1"
DocumenterCitations = "1"
Downloads = "1"
ExceptionUnwrapping = "0.1"
ExprRules = "1"
FFTW = "1"
GraphPPL = "0.3.1"
Graphs = "1"
JSON3 = "1"
LinearAlgebra = "1"
MacroTools = "0.5"
OhMyREPL = "0.5"
Parameters = "0.12"
Pkg = "1"
Plots = "1"
Preferences = "1"
Printf = "0.3"
ProgressMeter = "1"
Random = "1"
Requires = "1"
Rocket = "2.2.0"
SparseArrays = "1"
StaticArrays = "1"
Statistics = "1"
StatsBase = "0.33, 0.34"
StatsFuns = "1"
StructArrays = "0.6"
TerminalLoggers = "0.1"
Test = "1"
TimerOutputs = "0.5"
TinyHugeNumbers = "0.1"
UUIDs = "1"
UnPack = "1"
YAML = "0.4"
ZippedArrays = "0.1"

[extras]
Arpack = "7d9fca2a-8960-54d3-9f78-7d0dccf23c77"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "da2249de-2a9a-4A44-8149-85257299c5d7"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FFTW = "7a137065-842a-5206-8c79-ade2d9133a24"
OhMyREPL = "5593457a-c033-5973-8894-eb43b4a1a44a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[name]
name = "RxInfer"

[targets]
bench = ["BenchmarkTools", "DataFrames", "Plots"]
docs = ["Documenter", "DocumenterCitations", "Plots", "YAML"]
test = ["Test", "Arpack", "FFTW", "Downloads"]

[version]
version = "3.0.0-beta.0"
